#! /usr/bin/env zsh

SPACESHIP_PROMPT_ORDER=(
  git
  venv
  kubectl
  terraform
  user host dir
  char
)
SPACESHIP_RPROMPT_ORDER=(
  jobs
  exec_time
  time
)

SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_DEFAULT_PREFIX=$'\u2063'
SPACESHIP_PROMPT_DEFAULT_SUFFIX=$'\u2063'
SPACESHIP_PROMPT_DEFAULT_LINE_SUFFIX=" \n${SPACESHIP_PROMPT_DEFAULT_SUFFIX}"

SPACESHIP_GIT_PREFIX="${SPACESHIP_PROMPT_DEFAULT_PREFIX}"
SPACESHIP_GIT_SYMBOL="🐙 "
SPACESHIP_GIT_BRANCH_COLOR="202"
SPACESHIP_GIT_STATUS_UNTRACKED="❔"
SPACESHIP_GIT_STATUS_ADDED="➕"
SPACESHIP_GIT_STATUS_MODIFIED="✍️ "
SPACESHIP_GIT_STATUS_RENAMED="♻️ "
SPACESHIP_GIT_STATUS_DELETED="🗑 "
SPACESHIP_GIT_STATUS_STASHED="📬"
SPACESHIP_GIT_STATUS_AHEAD="⏩"
SPACESHIP_GIT_STATUS_BEHIND="⏪"
SPACESHIP_GIT_STATUS_DIVERGED="🔀"
SPACESHIP_GIT_SUFFIX="${SPACESHIP_PROMPT_DEFAULT_LINE_SUFFIX}"

SPACESHIP_TIME_SHOW=true

SPACESHIP_USER_SUFFIX=${SPACESHIP_PROMPT_DEFAULT_PREFIX}
SPACESHIP_HOST_PREFIX="@"
SPACESHIP_HOST_SUFFIX=" "

SPACESHIP_DIR_PREFIX=${SPACESHIP_PROMPT_DEFAULT_PREFIX}
SPACESHIP_DIR_LOCK_SYMBOL=" 🔒 "
SPACESHIP_DIR_SUFFIX="\n${SPACESHIP_PROMPT_DEFAULT_SUFFIX}"

SPACESHIP_VENV_SYMBOL="🐍 "
SPACESHIP_VENV_SUFFIX="${SPACESHIP_PROMPT_DEFAULT_LINE_SUFFIX}"
SPACESHIP_VENV_COLOR="green"

SPACESHIP_KUBECTL_PREFIX=${SPACESHIP_PROMPT_DEFAULT_PREFIX}
SPACESHIP_KUBECTL_SUFFIX="${SPACESHIP_PROMPT_DEFAULT_LINE_SUFFIX}"
SPACESHIP_KUBECTL_SYMBOL="☸️  "
SPACESHIP_KUBECTL_VERSION_SHOW=false
SPACESHIP_KUBECTL_async=false

SPACESHIP_TERRAFORM_SHOW=true
SPACESHIP_TERRAFORM_SUFFIX="${SPACESHIP_PROMPT_DEFAULT_LINE_SUFFIX}"
SPACESHIP_TERRAFORM_COLOR=128

SPACESHIP_CHAR_SYMBOL_SUCCESS="%{✨ %2G%} "
SPACESHIP_CHAR_SYMBOL_FAILURE="%{💩 %2G%} "
SPACESHIP_CHAR_SYMBOL_SECONDARY="➜ "
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_COLOR_SUCCESS="yellow"
SPACESHIP_CHAR_COLOR_FAILURE="94"

SPACESHIP_JOBS_SYMBOL=" ⚙ "
SPACESHIP_JOBS_SUFFIX=" "

SPACESHIP_EXEC_TIME_PREFIX="${SPACESHIP_PROMPT_DEFAULT_PREFIX}"
SPACESHIP_EXEC_TIME_SUFFIX=" ⌛ "
SPACESHIP_EXEC_TIME_COLOR="0"

SPACESHIP_TIME_PREFIX="${SPACESHIP_PROMPT_DEFAULT_PREFIX}"
SPACESHIP_TIME_SUFFIX=" 🕑 ${SPACESHIP_PROMPT_DEFAULT_SUFFIX}"
SPACESHIP_TIME_COLOR="0"

if [ "${SNAP_NAME}" = "intellij-idea-community" -o "${TERM_PROGRAM}" = "vscode" ]; then
  SPACESHIP_PROMPT_ORDER=(${SPACESHIP_RPROMPT_ORDER[@]} ${SPACESHIP_PROMPT_ORDER[@]})
  SPACESHIP_RPROMPT_ORDER=()
  SPACESHIP_TIME_SUFFIX="$SPACESHIP_TIME_SUFFIX\n${SPACESHIP_PROMPT_DEFAULT_SUFFIX}"
fi

fpath=("${HOME}/.config/shell/zsh/fpath" $fpath)
autoload -Uz promptinit
promptinit
prompt spaceship
eval "$(direnv hook zsh)"
